### ISSUE TITLE
稳定吗，大佬

### ISSUE THREAD

**Issue by hanlihanshaobo** [jayanta525/openwrt-nanopi-r2s#1]
可以直接编译了吗

**Comment by jayanta525** [comment]
porting from armbian and friendlyarm is not completed yet. this is a work in progress.

**Comment by hanlihanshaobo** [comment]
我看见你提交openwrt官网怎么样了？

**Comment by jayanta525** [comment]
first step is to completely add support to nanopi-r2s.
second is to create a pull request at openwrt github.
once the pull request goes in, create wiki page at openwrt.

**Comment by hanlihanshaobo** [comment]
> first step is to completely add support to nanopi-r2s.
> second is to create a pull request at openwrt github.
> once the pull request goes in, create wiki page at openwrt.

Probably how long it will take to complete

**Comment by jayanta525** [comment]
my board is not delivered yet. once i have the board, i can do my own testings.

**Comment by hanlihanshaobo** [comment]
> my board is not delivered yet. once i have the board, i can do my own testings.

ok，Thank you

**Comment by jayanta525** [comment]
Initial support for OpenWrt on NanoPi R2S has been added. Check release page for downloads.

**Comment by jayanta525** [comment]
https://github.com/jayanta525/openwrt-nanopi-r2s
