### ISSUE TITLE
about openssl speed

### ISSUE THREAD

**Issue by aptx17** [jayanta525/openwrt-nanopi-r2s#2]
Hello sir! any way to improve 16 bytes?

openssl speed -elapsed -evp aes-128-gcm   (with OpenWrt 1.5ghz)
![gcm](https://user-images.githubusercontent.com/41042297/82930097-645efe00-9fb7-11ea-99cc-4e07648ed58b.PNG)

---------------------------------------------------------------
openssl speed -elapsed -evp aes-128-gcm   (with FriendlyWrt 1.5ghz)
![FriendlyWrt-gcm](https://user-images.githubusercontent.com/41042297/82930293-b99b0f80-9fb7-11ea-8e58-58c1371bcd29.PNG)

**Comment by jayanta525** [comment]
I might have not included crypto in kernel for gcm. I will look into it.

Can you post the output for `cat /proc/crypto`

**Comment by aptx17** [comment]
> I might have not included crypto in kernel for gcm. I will look into it.
> 
> Can you post the output for `cat /proc/crypto`
yes,it here
[crypto.zip](https://github.com/jayanta525/openwrt-nanopi-r2s/files/4684045/crypto.zip)

**Comment by jayanta525** [comment]
seems like gcm crypto is included in kernel. I will test this when my board is delivered.

**Comment by aptx17** [comment]
okay,thanks.

**Comment by jayanta525** [comment]
@aptx17  

These are the results on the rk3328:

```
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      73199.42k   220411.12k   435064.21k   581664.88k   641874.92k   646187.19k
```

These results are much similar to FriendlyWrt. The only noticeable difference is on the values for **16 bytes** and **64 bytes**.

These differences may look huge in benchmarks, but in reality, it doesn't affect the crypto performance of the application using it.
