### ISSUE TITLE
DHCP may not work

### ISSUE THREAD

**Issue by shensven** [jayanta525/openwrt-nanopi-r2s#4]
Hi,bro
I downloaded your release, used `gzip -d` to decompress, got img file, then I used balenaEtcher flash sdcard.
after plug in the power supply, I can't got IP, DHCP not working?

<img width="1187" alt="Xnip2020-06-11_22-24-13" src="https://user-images.githubusercontent.com/16205980/84400223-5dc9bb00-ac34-11ea-9c61-ce934bd7c69c.png">

**Comment by jayanta525** [comment]
I remember adding `dnsmasq-full` and removing `dnsmasq`

This might be causing the DHCP issue. For reference, DHCP should be active on the eth1 interface.

I will update and create a new release asap. Please mention if you require any package included.

**Comment by carloscm** [comment]
It works for me. I flashed the ext4 image from this release:
https://github.com/jayanta525/openwrt-nanopi-r2s/releases/tag/v1.2

The LAN port has a dhcp server active and gives IPs in the 192.168.1.0/24 network.
The WAN port has a dhcp client active and can be used to connect to the internet.
Both of these default configurations worked for me on the first try, without having to change any config files.

**Comment by shensven** [comment]
Both of ext4 and squashfs I tried, same situation DHCP not work, It may be that the flashing method is wrong, first I format the sdcard to fat32, then use balenaEtcher, could share your flash method? @carloscm

**Comment by carloscm** [comment]
I'm on Windows 10 and I used Win32DiskImager 1.0.0, downloaded from the official Sourceforge page, a no-name cheap USB microsd adapter, and an even cheaper microsd card. I didn't format the card in advance, but at this point I've also formatted and overwrote it several times with no issues. I tested the card with H2testw beforehand tho, to make sure it wasn't fake (it was cheap but it wasn't a fake).

**Comment by jayanta525** [comment]
@shensven 

1. Download the img.gz file.
2. Open BalenaEtcher
3. Select the img.gz file
4. Select the drive
5. Burn the image

You don't have to extract the image file nor have to format the sd-card before writing. BalenaEtcher will do that for you.
 
It's highly unlikely that the sd-card burning method should affect the working of DHCP server. 

Please make sure that there aren't any DHCP server already active on the network the LAN port is connected to.

**Comment by shensven** [comment]
I used `sudo dd if=openwrt-rockchip-armv8-friendlyelec_nanopi-r2-rev00-squashfs-sysupgrade.img of=/dev/disk2 bs=32m` and flash succeeded, but the luci page show below:
<img width="1622" alt="Xnip2020-06-12_00-33-41" src="https://user-images.githubusercontent.com/16205980/84415400-4ba44880-ac45-11ea-914c-63502ae9d135.png">

**Comment by shensven** [comment]
DHCP works well, I got IP in the 192.168.1.0/24 network
