### ISSUE TITLE
Instructions to build 19.07.3 releases

### ISSUE THREAD

**Issue by mochaaP** [jayanta525/openwrt-nanopi-r2s#8]
Hello,

I'm trying to build an image of the 19.07.3 release, and I tried change `feeds.conf` to <https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/feeds.buildinfo> (all targets share the same file), but failed.
What's the exact method to achieve this?

Thanks.

**Comment by jayanta525** [comment]
Do you have any fail logs?

**Comment by mochaaP** [comment]
Building: <https://app.circleci.com/pipelines/github/mochaaP/openwrt-nanopi-r2s/6/workflows/e836c524-37ee-4331-99d4-80db03d2c812/jobs/6>

**Comment by jayanta525** [comment]
Thanks, I will look at it.

**Comment by jayanta525** [comment]
@mochaaP I didn't have any issues while compiling, https://app.circleci.com/pipelines/github/jayanta525/openwrt-nanopi-r2s/33/workflows/4198cd47-47ac-41f2-b8a9-4e180dd393e1/jobs/48

**Comment by mochaaP** [comment]
It's really weird. I reverted to the exact commit (except for `-j1 V=s`) but this time it failed to build the toolchain instead of the OpenWrt image.

The previous build is [here](https://app.circleci.com/pipelines/github/mochaaP/openwrt-nanopi-r2s/3/workflows/e7a167dc-2bef-4608-91ea-d3657306f7f9/jobs/3), with debug disabled.

Maybe it's my `config.seed`'s fault? Now I'm trying to build with your `config.seed` [here](https://app.circleci.com/pipelines/github/mochaaP/openwrt-nanopi-r2s/7/workflows/1f96d918-c890-43ab-b691-2d914d3dea14).

**Comment by jayanta525** [comment]
@mochaaP Yes, it's your config.seed. Have a look at my latest commit at circleci https://github.com/jayanta525/openwrt-nanopi-r2s/commit/4048ab8d5c44773c612abc8f796e4e05d7ff29cc.

**Comment by mochaaP** [comment]
Seems so. Closing this issue.

**Comment by mochaaP** [comment]
Just flashed, found it has some versioning problems, indicating it's a SNAPSHOT build but not a release build, although the revision is right.

On <https://github.com/jayanta525/openwrt-nanopi-r2s/commit/4048ab8d5c44773c612abc8f796e4e05d7ff29cc>:
![image](https://user-images.githubusercontent.com/21154023/88084462-0f0a2c00-cbb7-11ea-91b2-71e98b82dada.png)

On an official 19.07.3 release:
![image](https://user-images.githubusercontent.com/21154023/88084636-48db3280-cbb7-11ea-820e-7cec3ac18248.png)

**Comment by jayanta525** [comment]
Yes, its a SNAPSHOT build with 19.07.3 release feeds.
